import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { ReactScan } from "~/components/react-scan";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <ReactScan />
      <body>
        <TRPCReactProvider>
          <LayoutWrapper>{children}</LayoutWrapper>
        </TRPCReactProvider>
      </body>
    </html>
  );
}

const LayoutWrapper = ({ children }: Readonly<RootLayoutProps>) => {
  return (
    <div className="flex min-h-screen flex-col">
      <main className="mx-auto w-full max-w-screen-lg">{children}</main>
    </div>
  );
};
